#!/usr/bin/env bash
# display hours from 0 to 12 , minutes from 1 to 59

i=0
z=0
while [ "$i" -le "12" ] ; do
    echo "Hour: $z"
    n=1
    while [ "$n" -le "59" ] ; do
        echo "$n"
        ((n++))
    done
    ((z++))
    ((i++))
done
